platform :ios, '7.0'

target 'LumberjackLauncherExample' do
  pod 'CocoaLumberjack', '3.3.0'
  pod 'LumberjackConsole'

  target 'LumberjackLauncherExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
